@startuml

class CommunicationCANdroid extends Thread implements SocketListener
{
- receiveFrame() : void
+ connectClient() : void
+ disconnectClient() : void
+ sendFrame(frame : String) : void
}

@enduml